name: Deploy Next.js Application

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Merge PR
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false }}
      run: |
        git checkout master
        git merge --no-ff ${{ github.head_ref }}
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}