name: Deploy to Webhook

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the 'main' branch
      - develop
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specifies the environment to run the job on

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Replace with the Node.js version your project requires

    - name: Install dependencies
      run: npm install  # Replace with your package manager and install command

    - name: Build the project
      run: npm run build  # Replace with your build command

    - name: Trigger Deployment Webhook
      run: |
         curl -X GET https://b786-223-233-80-12.ngrok-free.app/deploy \
          -H "x-webhook-secret: ${{ secrets.WEBHOOK_SECRET_TOKEN }} " \
          -H "x-github-token: ${{secrets.GITHUB_TOKEN}} " \
          -H "x-github-repo: ${{github.repository}} " \
          -H "x-github-branch: ${{github.ref_name}} "
